#!/bin/sh
#
# $Id$
#
# (c) Copyright 2003 Adam W. Dace <adam@turing.com>  All Rights Reserved. 
# Please see the accompanying LICENSE file for license information.
#
CURRENT_DIR=`pwd`
INSTALL_DIR="/promo/distribulator2"

cd $INSTALL_DIR

./distribulator.py --directory=$CURRENT_DIR $1 $2 $3 $4 $5 $6 $7 $8
