#
# $Id$
#
PYTHON=/usr/local/bin/python

all:
	echo "Not implemented."

clean:
	rm config.log > /dev/null 2>&1
	rm config.status > /dev/null 2>&1
	rm distribulator.py > /dev/null 2>&1
	rm conf/config.xml > /dev/null 2>&1
	rm conf/logging.conf > /dev/null 2>&1
	rm scripts/distribulator.sh > /dev/null 2>&1
	find . -name '*.pyc' | xargs rm > /dev/null 2>&1
