#
# $Id$
#
PYTHON=/usr/local/bin/python

all:
	echo "Not implemented."

clean:
	find . -name '*~' | xargs rm > /dev/null 2>&1
	find . -name '*.pyc' | xargs rm > /dev/null 2>&1
	rm -rf autom4te*
	rm config.log > /dev/null 2>&1

